# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: framgia/laravel-workspace

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: chmod -R 777 storage
      - run: cp .env.example .env

      # Download and cache dependencies
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer-

      - run: composer install -n --prefer-dist
      - run: php artisan key:gen
      - run: if ! test -d ./vendor/squizlabs/php_codesniffer/src/Standards/Framgia; then git clone git@github.com:wataridori/framgia-php-codesniffer.git Framgia && mv ./Framgia ./vendor/squizlabs/php_codesniffer/src/Standards; fi

      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.json" }}

      - run: ./vendor/bin/phpcs --standard=Framgia app
      # run tests!
      - run: ./vendor/bin/phpunit
